Repository lizeth45/HDLC1, pull requests merged in 2022-11, with the labels that each got.

#11 Updated ghactions version
  .github/workflows/deploy.yml
Labels: bug

#12 Forced relative URLs
  .github/workflows/deploy.yml
  HDLC/CSS/estilos.css
  HDLC/CSS/style-index.css
  HDLC/IUPaciente.php
  HDLC/index.html
  HDLC/src/DoctorRegistro.php
  HDLC/src/LogIn.php
  HDLC/src/PacienteRegistro.php
  HDLC/src/Registro.php
  HDLC/src/SelecTU.php
  HDLC/src/connection/Conexiondb.php
Labels: bug

#14 Added dotenv lib
  .github/workflows/deploy.yml
  .gitignore
  HDLC/src/connection/Conexiondb.php
  HDLC/src/lib/dotenv/Dotenv.php
  HDLC/src/lib/dotenv/Exception/ExceptionInterface.php
  HDLC/src/lib/dotenv/Exception/InvalidEncodingException.php
  HDLC/src/lib/dotenv/Exception/InvalidFileException.php
  HDLC/src/lib/dotenv/Exception/InvalidPathException.php
  HDLC/src/lib/dotenv/Exception/ValidationException.php
  HDLC/src/lib/dotenv/Loader/Loader.php
  HDLC/src/lib/dotenv/Loader/LoaderInterface.php
  HDLC/src/lib/dotenv/Loader/Resolver.php
  HDLC/src/lib/dotenv/Parser/Entry.php
  HDLC/src/lib/dotenv/Parser/EntryParser.php
  HDLC/src/lib/dotenv/Parser/Lexer.php
  HDLC/src/lib/dotenv/Parser/Lines.php
  HDLC/src/lib/dotenv/Parser/Parser.php
  HDLC/src/lib/dotenv/Parser/ParserInterface.php
  HDLC/src/lib/dotenv/Parser/Value.php
  HDLC/src/lib/dotenv/Repository/Adapter/AdapterInterface.php
  HDLC/src/lib/dotenv/Repository/Adapter/ApacheAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ArrayAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/EnvConstAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/GuardedWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ImmutableWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/MultiReader.php
  HDLC/src/lib/dotenv/Repository/Adapter/MultiWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/PutenvAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ReaderInterface.php
  HDLC/src/lib/dotenv/Repository/Adapter/ReplacingWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ServerConstAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/WriterInterface.php
  HDLC/src/lib/dotenv/Repository/AdapterRepository.php
  HDLC/src/lib/dotenv/Repository/RepositoryBuilder.php
  HDLC/src/lib/dotenv/Repository/RepositoryInterface.php
  HDLC/src/lib/dotenv/Store/File/Paths.php
  HDLC/src/lib/dotenv/Store/File/Reader.php
  HDLC/src/lib/dotenv/Store/FileStore.php
  HDLC/src/lib/dotenv/Store/StoreBuilder.php
  HDLC/src/lib/dotenv/Store/StoreInterface.php
  HDLC/src/lib/dotenv/Store/StringStore.php
  HDLC/src/lib/dotenv/Util/Regex.php
  HDLC/src/lib/dotenv/Util/Str.php
  HDLC/src/lib/dotenv/Validator.php
  HDLC/src/lib/include.php
Labels: enhancement

#16 Updated deployment lib
  .github/workflows/deploy.yml
Labels: bug

#18 Updated database connection
  .github/workflows/deploy.yml
  .gitignore
  HDLC/src/connection/Conexiondb.php
  HDLC/src/lib/dotenv/Dotenv.php
  HDLC/src/lib/dotenv/Exception/ExceptionInterface.php
  HDLC/src/lib/dotenv/Exception/InvalidEncodingException.php
  HDLC/src/lib/dotenv/Exception/InvalidFileException.php
  HDLC/src/lib/dotenv/Exception/InvalidPathException.php
  HDLC/src/lib/dotenv/Exception/ValidationException.php
  HDLC/src/lib/dotenv/Loader/Loader.php
  HDLC/src/lib/dotenv/Loader/LoaderInterface.php
  HDLC/src/lib/dotenv/Loader/Resolver.php
  HDLC/src/lib/dotenv/Parser/Entry.php
  HDLC/src/lib/dotenv/Parser/EntryParser.php
  HDLC/src/lib/dotenv/Parser/Lexer.php
  HDLC/src/lib/dotenv/Parser/Lines.php
  HDLC/src/lib/dotenv/Parser/Parser.php
  HDLC/src/lib/dotenv/Parser/ParserInterface.php
  HDLC/src/lib/dotenv/Parser/Value.php
  HDLC/src/lib/dotenv/Repository/Adapter/AdapterInterface.php
  HDLC/src/lib/dotenv/Repository/Adapter/ApacheAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ArrayAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/EnvConstAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/GuardedWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ImmutableWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/MultiReader.php
  HDLC/src/lib/dotenv/Repository/Adapter/MultiWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/PutenvAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ReaderInterface.php
  HDLC/src/lib/dotenv/Repository/Adapter/ReplacingWriter.php
  HDLC/src/lib/dotenv/Repository/Adapter/ServerConstAdapter.php
  HDLC/src/lib/dotenv/Repository/Adapter/WriterInterface.php
  HDLC/src/lib/dotenv/Repository/AdapterRepository.php
  HDLC/src/lib/dotenv/Repository/RepositoryBuilder.php
  HDLC/src/lib/dotenv/Repository/RepositoryInterface.php
  HDLC/src/lib/dotenv/Store/File/Paths.php
  HDLC/src/lib/dotenv/Store/File/Reader.php
  HDLC/src/lib/dotenv/Store/FileStore.php
  HDLC/src/lib/dotenv/Store/StoreBuilder.php
  HDLC/src/lib/dotenv/Store/StoreInterface.php
  HDLC/src/lib/dotenv/Store/StringStore.php
  HDLC/src/lib/dotenv/Util/Regex.php
  HDLC/src/lib/dotenv/Util/Str.php
  HDLC/src/lib/dotenv/Validator.php
  HDLC/src/lib/include.php
Labels: bug

#23 Implemented common modules for <head>
  HDLC/assets/css/estilos.css
  HDLC/assets/css/login.css
  HDLC/assets/css/style-index.css
  HDLC/auth.php
  HDLC/index.php
  HDLC/login.php
  HDLC/paciente.php
  HDLC/src/apis/login.php
  HDLC/src/apis/sanitize.php
  HDLC/src/common/Head.php
Labels: bug, enhancement

#24 Updated login API consume
  .github/workflows/deploy.yml
  .gitignore
  HDLC/DoctorDetail.php
  HDLC/assets/css/style-IUPaciente.css
  HDLC/assets/js/scriptIUP.js
  HDLC/auth.php
  HDLC/login.php
  HDLC/paciente.php
  HDLC/src/apis/login.php
Labels: bug, enhancement

#26 Implemeted session handling
  HDLC/assets/css/style-IUPaciente.css
  HDLC/auth.php
  HDLC/index.php
  HDLC/login.php
  HDLC/logout.php
  HDLC/paciente.php
  HDLC/src/apis/login.php
Labels: bug, enhancement

#29 Added session_start()
  HDLC/doctor.php
Labels: bug

#30 Forms and apis update
  HDLC/auth.php
  HDLC/doctor.php
  HDLC/paciente.php
  HDLC/src/apis/generatePatientAppointment.php
  HDLC/src/apis/login.php
  HDLC/src/apis/updateDoctorData.php
  HDLC/src/apis/updatePatientData.php
Labels: bug, enhancement

#32 Update index.php / aboutHDLC
  HDLC/index.php
Labels: enhancement

#33 Added register.php
  HDLC/assets/css/register.css
  HDLC/assets/js/scriptIUP.js
  HDLC/auth.php
  HDLC/index.php
  HDLC/register.php
  HDLC/src/DoctorRegistro.php
  HDLC/src/PacienteRegistro.php
  HDLC/src/SelecTU.php
  HDLC/src/apis/_mailExists.php
  HDLC/src/apis/login.php
  HDLC/src/apis/registerDoctor.php
  HDLC/src/apis/registerPatient.php
Labels: bug, enhancement

#34 Update/All-Repo
  HDLC/DoctorDetail.php
  HDLC/assets/css/style-IUPaciente.css
  HDLC/assets/js/scriptIUP.js
  HDLC/deleteCita.php
  HDLC/doctor.php
  HDLC/paciente.php
  HDLC/src/apis/generatePatientAppointment.php
  HDLC/src/apis/login.php
  HDLC/src/apis/updateDoctorData.php
  HDLC/src/apis/updatePatientData.php
Labels: enhancement
